### PR TITLE
Changing visibility of longer property values

### PR DESCRIPTION
**Pull request by paireks**
Changing it helps with longer property values / keys. Without it, it shorten text really often.

### CODE REVIEW

**Comment by kovacsv** [comment]
Unfortunately it's not that easy. The website has two modes: Full UI, and Simplified (mobil) UI. The Full UI is available if the minimum window size is greater than 800 pixels. So for example if the window width is 850 pixels, then it definitely won't work if the sidebar is resizable to 800 pixel width.

Maybe it's possible to write a logic that sets the maximum sidebar size based on the current window width, but it needs some investigation.

**Comment by paireks** [comment]
Ok, hmm, I see, I will try to look at it

**Comment by paireks** [comment]
I tried some stuff with simple window.innerWidth to make it relative, but there were some other issues with it while resizing. I ended up with other solution that works even better, which is removing no-wrap to allow wrapping in CSS. It should look like in the GIF:
2022-10-29_22h40_06
For me practically it's better than current hiding, but then the question probably for Agnes is if it looks acceptable in terms of design :)

**Comment by kovacsv** [comment]
@Gaschitz what do you think? 🙂

**Comment by paireks** [comment]
If this solution seems to be problematic or ugly, then it can be anything else, just with ability to see the whole values :)

**Comment by Gaschitz** [comment]
We'd like to handle this question with a different approach and I've already created a new issue for that (#336) Thank you!

**Comment by Gaschitz** [comment]
And also this one 🙂  #337

**Pull request closed without merging**
