### PR TITLE
Allow initializing viewer element from File objects

### PR DESCRIPTION
**Pull request by iliazeus**
My use case is: I want to perform some transformations to the model before displaying it.

### CODE REVIEW

**Comment by kovacsv** [comment]
Thanks for the contribution. The two file sources (url and File) are handled with separate function throughout the code base, so I'd prefer to be consistent here as well.

I would do it with two functions:
- `Init3DViewerElementFromUrlList`
- `Init3DViewerElementFromFileList`

Also, please target the `dev` branch with contributions. Thanks!

**Comment by iliazeus** [comment]
> I would do it with two functions:
> 
> - `Init3DViewerElementFromUrlList`
> - `Init3DViewerElementFromFileList`

Renaming `Init3DViewerElement` to `Init3DViewerElementFromUrlList` would be a breaking change. Would that be OK?
I don't really like having both `Init3DViewerElement` and `Init3DViewerElementFromUrlList` that do exactly the same.

**Comment by kovacsv** [comment]
Breaking change is fine, I don't think a lot of people are using `Init3DViewerElement` directly, and I'm also planning to add a migration guide to the documentation. So feel free to rename the function. Please check if it is used by any examples in the `sandbox` folder.

**Comment by iliazeus** [comment]
Okay, I've renamed the function in engine code and in `sandbox` folder.

**Comment by kovacsv** [comment]
Merged, thanks a lot for your contribution!

**Pull request merged**
