### PR TITLE
Feature - 'ctrl + mouse left' zoom

### PR DESCRIPTION
**Pull request by hey24sheep**
Feature implementation of ctrl+mouse_left will zoom in/out like standard 3d viewers.

Tracking issue : #140

### CODE REVIEW

**Comment by kovacsv** [comment]
I've checked the code, and I think it doesn't work as expected. The zoom ratio should depend on the movement diff along the y axis. Now the code just decides the zoom direction based the y movement diff, and zoom works even if you move the mouse along the x axis only.

**Comment by hey24sheep** [comment]
I think zoom should be based on a fixed ratio for smooth experience otherwise it will cause the model to disappear (tiny or huge) based on the movement of mouse. I have added a check to disable the zoom if mouse is moved along x-axis. Have a look, let me what to change if you want to zoom based on delta instead on a fixed ratio, thanks.

**Comment by kovacsv** [comment]
I've modified the code a bit, now it seems fine for me. What do you think?

**Comment by hey24sheep** [comment]
Nice, I feel we could change `let zoomRatio = 0.001;` this value to `0.005` as current is slow and feels sluggish. LGTM overall.

**Comment by kovacsv** [comment]
I'm fine with changing the value to 0.005.

**Comment by hey24sheep** [comment]
Done

**Comment by kovacsv** [comment]
Thanks for the contribution.

**Pull request merged**
