### PR TITLE
Add optional edge displaying and settings

### LINKED ISSUE #44: Show Edges in 3D
Hi, 
Is there a way to show the edges with a black line ?

### PR DESCRIPTION
**Pull request by X-Ryl669**
This adds the display of edges and a dialog setting box that allows to enable it, set the angle (of edge detection) and edge colors.
This should close #44.

Teasing picture:
image

### CODE REVIEW

**Comment by X-Ryl669** [comment]
BTW, I don't know if you have a slider class (for `ov_dialog_slider`) that could be used instead of an (ugly) input box.

**Comment by kovacsv** [comment]
Hi @X-Ryl669!

Thank you for your contribution!

I find it a really good start, but I see some things that can be improved.
- It doesn't needed to reimport the model when only the edge visibility changes.
- Importer and viewer settings are mixed, I prefer to separate them.
- It doesn't handle edges during embedding, and for sharing and embedding link creation.

If that's ok for you, I can accept this pull request, but after that I'd like to modify your code a bit, so it can fit better to the existing logic. I'd also like to check the icon and dialog design with @Gaschitz as she is the designer for this development.

**Comment by X-Ryl669** [comment]
I've thought about this earlier. I came to the conclusion that showing edge is a view setting, not a model setting. At first I thought that it could be an attribute to a model, but it didn't worked from an ergonomic point of view (if you have multiple parts, it's strange). 



>     * It doesn't needed to reimport the model when only the edge visibility changes.

Yes. I'm not familiar enough with ThreeJS as I don't know how to retrieve the LinesGeometry mesh only to remove them when deselected. So I'm removing all meshes, thus need to import the model again. If you know how to do it correctly, please correct it.



>     * Importer and viewer settings are mixed, I prefer to separate them.

Right. 



>     * It doesn't handle edges during embedding, and for sharing and embedding link creation.

I think I don't get what you meant. For me, edge showing is a view attribute, not something that should be saved/shared.
I've added support for loading setting in embed code, but obviously, it need to be set from outside of the code. 



I'm perfectly ok for you to modify the code (in this PR or later) to fit your need. I've made the icon myself, it's genuine work with Inkscape. I've tried to keep the same "spirit" here (same line color, curves angle, line width, minimal design) but feel free to change it to better fit your graphism need. 

I've started adding a measure tool (not finished yet) to measure the distance between 2 parallel faces (and maybe the angle if not parallel) but it'll be in another PR.

**Comment by kovacsv** [comment]
> I think I don't get what you meant. For me, edge showing is a view attribute, not something that should be saved/shared.
I've added support for loading setting in embed code, but obviously, it need to be set from outside of the code.

I think it's a good idea to create embedding code or sharing link with the edges turned on. Embedding is used without programming knowledge so it would be nice to provide an easy solution to embed with edges. But of course, it can be skipped for now.

**Comment by kovacsv** [comment]
Sorry @X-Ryl669, but after I tested a bit I found a big error: When you show/hide a mesh the corresponding edges should be show/hide along with the relevant mesh. At the moment I don't know any way that it can be handled elegantly. If you have any idea, please let me know, but I don't think the current version is acceptable. :(

**Comment by X-Ryl669** [comment]
Arg. I'll fix this. What's missing is the same issue as I had with not reloading the mesh when changing the edge visibility: it's linking the edge with a specific mesh. I'll submit another PR today to fix this.

**Pull request merged**
