### PR TITLE
Explode Implode basic (need help)

### PR DESCRIPTION
**Pull request by hey24sheep**
Hi, I have added a basic (currently buggy, but works) explode implode feature. If anyone could help with math that would be great.

### CODE REVIEW

**Comment by kovacsv** [comment]
I could't help you with this one, but here are some comments.

- Explode should be a view-only feature, so it shouldn't affect the Mesh data structure.
- There are add and sub functions for coordinates already as separate functions.
- Explode distance should depend on the model size.
- Animation would be nice.

**Comment by Emilien-Etadam** [comment]
I don't know if it's help but there is a very good explode function here : https://www.3dvieweronline.com/members/Id9bf31c7ff062936a96d3c8bd1f8f2ff3/3VCKJVxOIM45tzr

Little trick to use it : 

change display : "none" by "Block" to show the button.

**Comment by hey24sheep** [comment]
@Emilien-Etadam I read the code and they are differently handling the code. They have a zip file containing parts of that whole model in .stl format and then they have multiple .txt files containing cords of that and then they have a solidworks file which binds everything together. Based on that they have a specific code written which doesn't work for our objects as we do not have those properties that they have in `explode function`. I am not a pro reverse-engineer or a debugger so, if anyone smarter than me can look at their code maybe that would help.

**Comment by kovacsv** [comment]
I close this due to inactivity.

**Pull request closed without merging**
